### ISSUE TITLE
Please release commit ref cda4f8 on RubyGems to support Mongoid 3.x

### ISSUE THREAD

**Issue by johnnyshields** [suweller/mongoid-autoinc#22]
Please cut a release on RubyGems as version 3.x.x (up to you) at ref: cda4f81cb5c605ea8ce799473ab40af7a42397b2

This is the last ref which supports Mongoid 3.

**Comment by thiensubs** [comment]
Please update gem to support mongoid 5.x.x, because i'm using rpush-mongoid, it depend this gem.
So i can do any thing with rpush gem. :(

**Comment by suweller** [comment]
@johnnyshields, I have little time to keep working on `mongoid-autoinc`, as at my current job, we do not use mongodb, let alone mongoid-autoinc.
Would you care to also be able to release gems? If you are, please 
Or do you maybe know someone who would be interested?

**Comment by suweller** [comment]
I see you live in Japan, so I'll be asleep as you go about most of your day. Because I've seen the code you're already a `Collaborator` I see no reason for you not to also have gem publish rights. If you don't want it, let me know, so we can start looking for someone else.

@matsimitsu, are you okay with this development also?

**Comment by matsimitsu** [comment]
Works for me! :+1:
